#!/usr/bin/env bash
# Display information about subdomains
domain_check() {
  # Check for a valid domain
  subdomains=("www" "web-01" "web-02" "lb-01")

  # check if a subdomain is given as the second argument($2)
    if [ -z "$2" ]; then
    # if ($2) is empty, then loop through all subdomains in subdomain array
	for subdomain in "${subdomains[@]}"; do
	    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, DOMAIN, "."); print "The subdomain " DOMAIN[1] " is a " $4 " record and points to " $5}'
	done

    # if ($2) is not empty, then print the information about the given subdomain($2)
    else
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{split($0, DOMAIN, "."); print "The subdomain " DOMAIN[1] " is a " $4 " record and points to " $5}'
    fi
}
domain_check "$1" "$2"
