#!/usr/bin/env bash
# This script installs nginx on the server it's executed on, sets listening
# port as 80 and creates a default html file that returns Hello World! when queried

# Update package lists
sudo apt update

# Install nginx
sudo apt install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create a temporary index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
