#!/usr/bin/env bash
# Configure an ubuntu server with haproxy - load balancer
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
sudo cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
      frontend haproxy-main
        bind *:80
        option forwardfor
        default_backend nginx_webservers

      backend nginx_webservers
        balance roundrobin
        server 263183-web-01        34.224.17.48:80 check
        server 263183-web-02        100.25.159.194:80 check
EOF
sudo service haproxy restart
