#!/usr/bin/env bash
# Handles curl: (7) Failed to connect to 0 port 80: Connection refused
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart